FIX text language bug, variations order and base price
plentymarkets/plugin-elastic-export-guenstiger-de pull request #2
Opened 2017-05-15 13:01 UTC by alinmigea

@plentymarkets/team-multichannel-koboldmaki

2017-05-15 13:03 UTC, mariusbippig requested changes

2017-05-15 13:03 UTC, Desentyer commented on meta/documents/changelog_de.md
> +- Es wurde ein Fehler behoben, bei dem Varianten nicht in der richtigen Reihenfolge gelisted wurde.
"....gelistet wurden."

2017-05-16 09:13 UTC, alinmigea commented
@Desentyer here is everything ok? can you take a look again, I've corrected the change logs

2017-05-16 12:22 UTC, mariusbippig approved these changes

2017-05-16 12:41 UTC, merged